version: '2'
services:
  app:
    build:
      context: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3333:3333
    links:
      - mysql
    command: npm start

  # # #######################################
  # # # MySQL server
  # # #######################################
  mysql:
    image: mariadb:10.3
    ports:
      - 3306:3306
    volumes:
      # - /tmp/debug/:/tmp/debug/
      - ./etc/mysql/:/etc/mysql/conf.d/
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=boobytrapp

  # # #######################################
  # # # Redis
  # # #######################################
  # redis:
  #  image: redis:3
